"""empty message

Revision ID: 2996c5dba7ed
Revises: 0513e0ae8c16
Create Date: 2020-02-14 22:33:39.545958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2996c5dba7ed'
down_revision = '0513e0ae8c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
